apiVersion: v1
kind: Pod
metadata:
  name: testED
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: containerEd
    volumeMounts: 
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}