apiVersion: v1
kind: Service
metadata:
  name: nova-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort  
  ports:
    - nodeport: 31000
      port: 80
      targetPort: 80